### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by KrzysztofMadejski** [deepdata-ltd/indicator-toolbox#1]
Is the resulting JAR giving any interfaces that allows to deploy it in Tomcat or other Java EE Server? What's the tech behind this project? What Http server does the jar run?

**Comment by juzraai** [comment]
The project is built on top of [Spring Boot](https://projects.spring.io/spring-boot/) framework, the JAR file contains it's own embedded (Tomcat) server. You can [run the app](https://github.com/deepdata-ltd/indicator-toolbox#running) as a regular JAR file, only a JRE is required.

If necessary, I can enable the "run as service" feature then you can [install the application as a service](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html). After that you can easily start/stop/restart it and the OS will launch it after booting.
